# Generated by Django 2.1.5 on 2019-01-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='last_id',
            new_name='last_ip',
        ),
    ]
