# Generated by Django 2.1.5 on 2019-01-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.FileField(null=True, upload_to='avatars/', verbose_name='头像'),
        ),
    ]
