# Generated by Django 2.1.5 on 2019-01-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.FileField(null=True, upload_to='aaaaa/', verbose_name='头像'),
        ),
    ]
